package com.globe3.tno.g3_mobile.model.entities;

import java.io.Serializable;
import java.util.Date;

public class dailytime implements Serializable{
	public long idcode;
	public String tag_table_usage;
	public String sync_unique;
	public String uniquenum_pri;
	public String uniquenum_sec;
	public String tag_void_yn;
	public String tag_deleted_yn;
	public Date date_post;
	public Date date_submit;
	public Date date_sync;
	public Date date_lastupdate;
	public String userid_creator;
	public String masterfn;
	public String companyfn;
	public String staff_unique;
	public String staff_id;
	public String staff_fullname;
	public String type_in_out;
	public Date date_time_in;
	public Date date_time_out;
	public String gps_location_in;
	public String gps_location_out;
	public String device_id_in;
	public String device_id_out;
	public String project_code;
	public String project_name;
	public String project_unique;
	public String job_code;
	public String job_unique;
	public String task_code;
	public String task_unique;
	public String nvar25_01;
	public String nvar25_02;
	public String nvar25_03;
	public String nvar100_01;
	public String nvar100_02;
	public String nvar100_03;
	public String nvar100_04;
	public Date date01;
	public Date date02;
	public float num01;
	public float num02;
	public String sale_order_code;
	public String sale_order_name;
	public String sale_order_unique;
}
