package com.globe3.tno.g3_mobile.model.entities;

import java.io.Serializable;
import java.util.Date;

public class staffdata implements Serializable{
	public long idcode;
	public String tag_table_usage;
	public String sync_unique;
	public String uniquenum_pri;
	public String uniquenum_sec;
	public String active_yn;
	public Date date_post;
	public Date date_submit;
	public Date date_lastupdate;
	public Date date_sync;
	public String userid_creator;
	public String masterfn;
	public String companyfn;
	public String co_code;
	public String co_name;
	public String own_staff_yn;
	public String staff_group;
	public String pay_group;
	public String nationality;
	public String gender;
	public String race;
	public String religion;
	public String job_title;
	public String staff_unique;
	public String staff_id;
	public String staff_fullname;
	public String staff_type;
	public String workpermit_type;
	public String workpermit_num;
	public Date workpermit_issuedate;
	public Date workpermit_expirydate;
	public Date work_startdate;
	public Date work_ceasedate;
	public String supervisor_name;
	public String supervisor_unique;
	public String vendor_name;
	public String vendor_unique;
	public Date date_birth;
	public byte[] photo1;
	public byte[] photo2;
	public byte[] fingerprint_image1;
	public byte[] fingerprint_image2;
	public byte[] fingerprint_image3;
	public byte[] fingerprint_image4;
	public byte[] fingerprint_image5;
	public String project_code;
	public String project_name;
	public String project_unique;
}
